apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: default
  labels:
    app: user-management-app
spec:
  selector:
    app: user-management-app
  ports:
  - name: signup
    port: 80
    targetPort: 5000
    protocol: TCP
  - name: list
    port: 8080
    targetPort: 5001
    protocol: TCP
  type: ClusterIP